export const FETCH_REFERENCES_PENDING = "FETCH_REFERENCES_PENDING";
export const FETCH_REFERENCES_SUCCESS = "FETCH_REFERENCES_SUCCESS";
export const FETCH_REFERENCES_ERROR = "FETCH_REFERENCES_ERROR";
